/**
 * 翻译字典模块
 * 
 * safeGlobalDict:  安全长句字典，不会与代码变量冲突，可直接全局替换
 * riskyShortWords: 危险短词字典，只能在 UI 属性上下文中替换，否则会导致白屏
 */

const safeGlobalDict = {
    "Manage Account": "管理账号",
    "Manage your account and billing": "管理您的账号与账单",
    "Invite Team Members": "邀请团队成员",
    "Accelerate development, shared knowledge, and context across your team": "跨团队加速开发并共享知识与上下文",
    "Preferences": "偏好设置",
    "Sync layouts across windows": "跨窗口同步布局",
    "When enabled, all windows share the same layout": "启用后，所有窗口共享相同的布局",
    "Editor Settings": "编辑器设置",
    "Configure font, formatting, minimap and more": "配置字体、格式化、缩略图等",
    "Keyboard Shortcuts": "键盘快捷键",
    "Configure keyboard shortcuts": "配置键盘快捷键",
    "Import Settings from VS Code": "从 VS Code 导入设置",
    "Import settings, extensions, and keybindings from VS Code": "导入 VS Code 的设置、扩展和快捷键绑定",
    "See warnings and tips that you've hidden": "查看您已隐藏的警告和提示",
    "Layout": "布局",
    "Status Bar": "状态栏",
    "Show status bar": "显示状态栏",
    "Auto-hide editor when empty": "空闲时自动隐藏编辑器",
    "When all editors are closed, hide the editor area and maximize chat": "关闭所有编辑器时，隐藏编辑器并最大化聊天窗口",
    "Notifications": "通知",
    "Warning Notifications": "警告通知",
    "Show warning-level in-app toasts.": "显示应用内警告级别提示。",
    "Cursor Account": "Cursor 账号",
    "Plan & Usage": "套餐与用量",
    "New Agent": "新建智能体",
    "Customize": "自定义界面",
    "Repositories": "代码仓库",
    "Tools & MCPs": "工具与 MCP",
    "System Notifications": "系统通知",
    "Show system notifications when Agent completes or needs attention": "智能体完成任务或需要注意时显示系统通知",
    "System Tray Icon": "系统托盘图标",
    "Show Cursor in system tray": "在系统托盘显示 Cursor",
    "Completion Sound": "完成提示音",
    "Play a sound when Agent finishes responding": "智能体完成响应时播放提示音",
    "Privacy": "隐私",
    "Rules, Skills, Subagents": "规则、技能与子智能体",
    "Tools & MCP": "工具与 MCP",
    "Indexing & Docs": "索引与文档",
    "Cloud Agents": "云端智能体",
    "Team Plan": "团队版",
    "Plugins": "插件",
    "Search settings": "搜索设置",
    "Auto-Run Mode": "自动运行模式",
    "Choose how Agent runs tools like command execution, MCP, and file writes.": "选择智能体如何运行命令执行、MCP 和文件写入等工具。",
    "Command Allowlist": "命令白名单",
    "Commands that can run automatically": "可自动运行的命令",
    "MCP Allowlist": "MCP 白名单",
    "MCP tools that can run automatically. Format: 'server:tool', 'server:*' for all tools from a server, '*:tool' for a tool from any server, or *:* for all tools from all servers": "可自动运行的 MCP 工具。格式：'server:tool'、'server:*' 表示某服务器的全部工具、'*:tool' 表示任意服务器的某工具、*:* 表示所有服务器的所有工具",
    "Fetch Domain Allowlist": "请求域名白名单",
    "Domains that Agent can fetch from automatically. Use '*' for all domains, '*.example.com' for wildcard subdomains.": "智能体可自动请求的域名。使用 '*' 匹配所有域名，'*.example.com' 匹配通配符子域名。",
    "Auto-Approved Mode Transitions": "自动批准的模式切换",
    "Mode transitions that will be automatically approved without prompting.": "无需提示即自动批准的模式切换。",
    "Browser Protection": "浏览器保护",
    "Prevent Agent from automatically running Browser tools": "阻止智能体自动运行浏览器工具",
    "MCP Tools Protection": "MCP 工具保护",
    "Prevent Agent from automatically running MCP tools": "阻止智能体自动运行 MCP 工具",
    "File-Deletion Protection": "文件删除保护",
    "Prevent Agent from deleting files automatically": "阻止智能体自动删除文件",
    "External-File Protection": "外部文件保护",
    "Prevent Agent from creating or modifying files outside of the workspace automatically": "阻止智能体自动创建或修改工作区外的文件",
    "Default Location": "默认位置",
    "Where to open new agents": "新智能体的打开位置",
    "Text Size": "文字大小",
    "Adjust the conversation text size": "调整对话文字大小",
    "Ask Every Time": "每次询问",
    "Use Allowlist": "使用白名单",
    "Run Everything": "运行所有",
    "Settings": "设置",
    "Extra Large": "超大",
    "Cursor Tab": "Cursor Tab 补全",
    "Context-aware, multi-line suggestions around your cursor based on recent edits": "基于最近编辑，在光标周围提供上下文感知的多行建议",
    "Partial Accepts": "部分接受",
    "Accept the next word of a suggestion via Ctrl+RightArrow": "通过 Ctrl+右箭头接受建议的下一个单词",
    "Suggestions While Commenting": "注释时建议",
    "Allow Tab to trigger while in a comment region": "允许在注释区域中触发 Tab 补全",
    "Whitespace-Only Suggestions": "仅空白建议",
    "Suggest edits like new lines and indentation that modify whitespace only": "仅建议修改空白的编辑，如换行和缩进",
    "Automatically import necessary modules for TypeScript": "自动导入 TypeScript 所需的模块",
    "Auto Import for Python": "Python 自动导入",
    "Enable auto import for Python. This is a beta feature.": "启用 Python 自动导入。这是一个测试功能。",
    "Provide domain-specific knowledge and workflows for the agent": "为智能体提供特定领域的知识和工作流",
    "Include third-party Plugins, Skills, and other configs": "包含第三方插件、技能和其他配置",
    "Automatically import agent configs from other tools": "自动从其他工具导入智能体配置",
    "Use Rules to guide agent behavior, like enforcing best practices or coding standards. Rules can be applied always, by file path, or manually.": "使用规则引导智能体行为，例如强制执行最佳实践或编码标准。规则可以始终应用、按文件路径应用或手动应用。",
    "Skills are specialized capabilities that help the agent accomplish specific tasks. Skills will be invoked by the agent when relevant or can be triggered manually with / in chat.": "技能是帮助智能体完成特定任务的专业能力。智能体会在相关时自动调用技能，也可在聊天中通过 / 手动触发。",
    "No Skills Yet": "暂无技能",
    "Skills help the agent accomplish specific tasks": "技能帮助智能体完成特定任务",
    "New Skill": "新建技能",
    "Create specialized agents for complex tasks. Subagents can be invoked by the agent to handle focused work in parallel.": "创建用于复杂任务的专业智能体。子智能体可被主智能体调用，以并行处理专项工作。",
    "No Subagents Yet": "暂无子智能体",
    "Create specialized agents to handle focused tasks": "创建专业智能体来处理专项任务",
    "New Subagent": "新建子智能体",
    "Create reusable workflows triggered with / prefix in chat. Use commands to standardize processes and make common tasks more efficient.": "创建在聊天中通过 / 前缀触发的可复用工作流。使用命令标准化流程，提高常见任务的效率。",
    "No Commands Yet": "暂无命令",
    "Create commands to build reusable workflows": "创建命令以构建可复用工作流",
    "New Command": "新建命令",
    "+ New": "+ 新建",

    // ── 智能体设置 ──
    "Auto-Clear Chat": "自动清除聊天",
    "After periods of inactivity, open the Agent Pane to a new conversation": "一段时间不活动后，将智能体面板打开为新对话",
    "Submit with Ctrl + Enter": "使用 Ctrl + Enter 提交",
    "When enabled, Ctrl + Enter submits chat and Enter inserts a newline": "启用后，Ctrl + Enter 提交聊天，Enter 插入换行",
    "Max Tab Count": "最大标签页数",
    "Limit how many chat tabs can be open at once": "限制同时打开的聊天标签页数量",
    "Queue Messages": "消息队列",
    "Adjust the default behavior of sending a message while Agent is running": "调整智能体运行时发送消息的默认行为",
    "Send after current message": "当前消息后发送",
    "Stop & send right away": "立即停止并发送",
    "Usage Summary": "用量摘要",
    "When to show the usage summary at the bottom of the chat pane": "何时在聊天面板底部显示用量摘要",
    "Agent Autocomplete": "智能体自动补全",
    "Contextual suggestions while prompting Agent": "向智能体提问时提供上下文建议",

    // ── Agent Review ──
    "Start Agent Review on Commit": "代码提交时启动智能体审查",
    "Automatically review your changes for issues after each commit": "在每次提交后自动审查您的更改是否存在问题",
    "Include Submodules in Agent Review": "在智能体审查中包含子模块",
    "Include changes from Git submodules in the review": "在审查中包含 Git 子模块的更改",
    "Include Untracked Files in Agent Review": "在审查中包含未跟踪文件",
    "Include untracked files (new files not yet added to Git) in the review": "在审查中包含未跟踪文件（尚未添加到 Git 的新文件）",
    "Default Approach": "默认方式",
    "Choose between quick or more thorough, higher-cost analysis": "选择快速或更彻底、成本更高的分析",

    // ── Context & Applied Changes ──
    "Web Search Tool": "网络搜索工具",
    "Allow Agent to search the web for relevant information": "允许智能体在网络上搜索相关信息",
    "Auto-Accept Web Search": "自动接受网络搜索",
    "Skip approval dialog; Agent may run web searches automatically": "跳过批准对话；智能体可自动运行网络搜索",
    "Web Fetch Tool": "网页获取工具",
    "Allow Agent to fetch content from URLs": "允许智能体从 URL 获取内容",
    "Hierarchical Cursor Ignore": "分层 Cursor 忽略",
    "Apply .cursorignore files to all subdirectories. Changing this setting will require a restart of Cursor.": "将 .cursorignore 文件应用到所有子目录。更改此设置需要重启 Cursor。",
    "Ignore Symlinks in Cursor Ignore Search": "在 Cursor 忽略搜索中忽略符号链接",
    "Use with caution. Skip symlinks during .cursorignore file discovery. Only enable if your repository has many symlinks and all .cursorignore files are reachable without them. Changing this setting will require a restart of Cursor.": "谨慎使用。在发现 .cursorignore 文件时跳过符号链接。仅当您的仓库存有许多符号链接，且没有符号链接也能访问所有 .cursorignore 文件时才启用。更改此设置需要重启 Cursor。",
    "Applying Changes": "应用更改",
    "Inline Diffs": "内联差异",
    "Show inline diff decorations in the editor instead of only showing changes in the review panel": "在编辑器中显示内联差异装饰，而不是仅在审查面板中显示更改",
    "Jump to Next Diff on Accept": "接受时跳转到下一个差异",
    "Automatically jump to the next diff when accepting changes with Ctrl+Y": "使用 Ctrl+Y 接受更改时自动跳转到下一个差异",
    "Auto Format on Agent Finish": "智能体完成时自动格式化",
    "Automatically format files when the agent finishes": "智能体完成任务时自动格式化文件",

    // ── Inline Editing & Terminal ──
    "Inline Editing & Terminal": "内联编辑与终端",
    "Legacy Terminal Tool": "旧版终端工具",
    "Use the legacy terminal tool in agent mode, for use on systems with unsupported shell configurations": "在智能体模式下使用旧版终端工具，适用于 shell 配置不受支持的系统",
    "Toolbar on Selection": "选中时显示工具栏",
    "Show Add to Chat & Quick Edit buttons when selecting code": "选择代码时显示“添加到聊天”和“快速编辑”按钮",
    "Auto-Parse Links": "自动解析链接",
    "Automatically parse links when pasted into Quick Edit (Ctrl+K) input": "粘贴到快速编辑 (Ctrl+K) 输入框时自动解析链接",
    "Themed Diff Backgrounds": "主题差异背景",
    "Use themed background colors for inline code diffs": "为内联代码差异使用主题背景色",
    "Terminal Hint": "终端提示",
    "Show a hint for Ctrl+K in the Terminal": "在终端中显示 Ctrl+K 提示",
    "Preview Box for Terminal Ctrl+K": "终端 Ctrl+K 的预览框",
    "Use a preview box instead of streaming responses directly into the shell": "使用预览框而不是将响应直接流式传输到 shell 中",
    "Collapse Auto-Run Commands": "折叠自动运行命令",
    "Collapse auto-run command output by default in Terminal command previews": "在终端命令预览中默认折叠自动运行的命令输出",

    // ── Voice Mode & Attribution ──
    "Voice Mode": "语音模式",
    "Submit Keywords": "提交关键字",
    "Custom keywords that trigger auto-submit in voice mode. Only single words (no spaces) are allowed. Punctuation and capitalization are ignored.": "在语音模式下触发自动提交的自定义关键字。仅允许单个单词（无空格）。忽略标点符号和大小写。",
    "Attribution": "代码署名",
    "Commit Attribution": "提交署名",
    "Mark Agent commits as 'Made with Cursor'": "将智能体提交标记为 'Made with Cursor'",
    "PR Attribution": "PR 署名",
    "Mark pull requests as made with Cursor": "将拉取请求标记为使用 Cursor 制作",

    // ── Privacy ──
    "Privacy Mode": "隐私模式",
    "Your code data will not be trained on or used to improve the product. Code may be stored to provide features such as Background Agent.": "您的代码数据不会被用于训练或改进产品。代码可能会被存储以提供后台智能体等功能。",
    "Data Sharing is controlled by the team admin. Configure here.": "数据共享由团队管理员控制。在此配置。",

    // ── Miscellaneous ──
    "Accept the next word of a suggestion via Ctrl+RightArrow": "通过 Ctrl+RightArrow 接受建议的下一个词",
    "Automatically import necessary modules for TypeScript": "自动为 TypeScript 导入必要的模块",

    // ── Usage Limits ──
    "Increase limits for faster responses": "提高限制以获得更快的响应",
    "You're over your current usage limit and your requests are being processed with Auto in the slow queue.": "您已超出当前配置的使用量限制，您的请求正以临时排队方式在慢速队列中处理。",
    "Set new limit": "设置新限制",

    // ── Cloud / Background Agents ──
    "Get Started": "开始使用",
    "Cloud Agents require a Git repository in an open folder.": "云智能体需要打开的文件夹中包含 Git 仓库。",
    "Open a Git repository": "打开 Git 仓库",
    "Background agents only work in folders with a git repository.": "后台智能体仅在包含 git 仓库的文件夹中工作。",
    "Please open a folder that contains a git repository to use this feature.": "请打开包含 git 仓库的文件夹以使用此功能。",

    // ── Extensions / Marketplace ──
    "Extend Cursor with Skills, Rules, Agents, Hooks, and MCPs": "使用技能、规则、智能体、钩子和 MCP 扩展 Cursor",

    // ── Network ──
    "HTTP Compatibility Mode": "HTTP 兼容模式",
    "HTTP/2 is recommended for low-latency streaming. In some corporate proxy and VPN environments, the compatibility mode may need to be lowered.": "推荐使用 HTTP/2 以实现低延迟流式传输。在某些企业代理和 VPN 环境中，可能需要降低兼容模式。",
    "Required Domains": "必需的域名",
    "These domains must be accessible for Cursor to function. Add them to your firewall or proxy allowlist.": "必须可访问这些域名，Cursor 才能正常工作。请将它们添加到您的防火墙或代理白名单中。",
    "Network Diagnostics": "网络诊断",
    "Check network connectivity to all Cursor services": "检查与所有 Cursor 服务的网络连接",

    // ── Update ──
    "Update Access": "更新通道",
    "By default, get notifications for stable updates. In Early Access, pre-release builds may be unstable for production work.": "默认情况下，接收稳定版更新的通知。在抢先体验通道中，预发布版本可能不稳定，不建议用于生产环境。",
    "Extension RPC Tracer": "扩展 RPC 追踪器",
    "Log extension host RPC messages to JSON files viewable in Perfetto for performance analysis. Requires a restart to take effect.": "将扩展主机的 RPC 消息记录到 JSON 文件中，可在 Perfetto 中查看以进行性能分析。需要重启才能生效。",

    // ── Hooks ──
    "Hooks let you run custom scripts at specific points during the agent's execution to modify behavior, enforce policies, or add custom logging.": "钩子允许您在智能体执行的特定点运行自定义脚本，以修改行为、强制执行策略或添加自定义日志。",
    "No hooks configured": "未配置钩子",
    "No hook executions yet": "暂无钩子执行记录",

    // ── Tools / Browser ──
    "Browser Automation": "浏览器自动化",
    "Browser automation disabled": "浏览器自动化已禁用",
    "Show Localhost Links in Browser": "在浏览器中显示 Localhost 链接",
    "Automatically open localhost links in the Browser Tab": "自动在浏览器标签页中打开 localhost 链接",

    // ── Features / Documentation Links ──
    "Learn about Rules": "了解规则",
    "Learn about Skills": "了解技能",
    "Learn about Subagents": "了解子智能体",
    "Learn about Commands": "了解命令",
    "User Rule": "用户规则",
    "Project Rule": "项目规则",
    "Add from GitHub/GitLab": "从 GitHub/GitLab 添加",

    // ── Commands & MCP ──
    "Project Command": "项目命令",
    "User Command": "用户命令",
    "New MCP Server": "新建 MCP 服务器",
    "Add a Custom MCP Server": "添加自定义 MCP 服务器",

    // ── Models ──
    "Balanced quality and speed, recommended for most tasks": "平衡质量和速度，推荐用于大多数任务",
    "Multiple models require a Git repository.": "使用多模型功能需要 Git 仓库。",

    // ── Dialogs ──
    "Are you sure? This replaces your settings and extensions with your vscode ones. This cannot be undone.": "确定要继续吗？这将用您的 VS Code 设置和扩展替换当前的设置和扩展。此操作无法撤销。",
    "Reset \"Don't Ask Again\" Dialogs": "重置“不再询问”弹窗",
    "Reset \"Don’t Ask Again\" Dialogs": "重置“不再询问”弹窗",
    "See warnings and tips that you've hidden": "查看您已隐藏的警告和提示",
    "See warnings and tips that you’ve hidden": "查看您已隐藏的警告和提示",
    "No Hidden Dialogs Yet": "暂无隐藏的弹窗",
    "You haven't marked any dialogs as \"Don't ask again\". Any hidden dialogs will appear here to manage.": "您尚未将任何弹窗标记为“不再询问”。任何隐藏的弹窗都将显示在此处以供管理。",
    "You haven’t marked any dialogs as \"Don’t ask again\". Any hidden dialogs will appear here to manage.": "您尚未将任何弹窗标记为“不再询问”。任何隐藏的弹窗都将显示在此处以供管理。",

    // ── 下面原本误放入了短词字典 ──
    "Submit with ": "使用 ",
    "When enabled, ": "启用后，",
    " submits chat and ": " 提交聊天，",
    " inserts a newline": " 插入换行",
    "Accept the next word of a suggestion via ": "使用 ",
    " accept the next word of a suggestion": " 接受建议的下一个词",
    "Automatically import necessary modules for TypeScript": "自动为 TypeScript 导入必要的模块",

    // Codebase 相关设置
    "Codebase": "代码库",
    "Codebase Indexing": "代码库索引",
    "Delete Index": "删除索引",
    "Index New Folders": "索引新文件夹",
    "Automatically index any new folders with fewer than 250,000 files": "自动索引少于 250,000 个文件的新文件夹",
    "View included files.": "查看已包含的文件。",
    "Team-Level Repository Control": "团队级代码库控制",
    "Disable AI features in specific repositories based on file pattern": "基于文件匹配模式在特定代码库中禁用 AI 功能",
    "Index Repositories for Instant Grep": "为 Instant Grep 索引代码库",
    "Automatically index repositories to speed up Grep searches. All data is stored locally.": "自动索引代码库以加速 Grep 搜索。所有数据均存储在本地。",
    "Crawl and index custom resources and developer docs": "爬取并索引自定义资源和开发者文档",
    "No Docs Added": "未添加文档",
    "Add Doc": "添加文档",
    "Increase limits for faster responses": "提升额度以获取更快响应",
    "Automatically jump to the next diff when accepting changes with ": "当接受更改时，自动跳转到下一个差异，借助 ",
    "Ignore Files in ": "忽略包含在 ",
    "Ignore Files in .cursorignore": "忽略 .cursorignore 中的文件",
    "Nightly Updates Apply Automatically": "每夜更新自动应用",
    "Copy Domains": "复制域名",
    "Run Diagnostic": "运行诊断",
    "Learn about codebase indexing": "了解代码库索引",
    "Embed codebase for improved contextual understanding and knowledge. Embeddings and metadata are stored in the": "嵌入代码库以增强上下文理解和知识。嵌入向量和元数据存储在",
    ", but all code is stored locally.": "，但所有代码都存储在本地。",
    "Agent Review": "智能体审查",
    "Data Sharing is controlled by ": "数据共享由",
    "team admin.": "团队管理员控制。",
    "Nightly builds will silently download and install updates without prompting you.": "每夜版本将静默下载并安装更新，不会提示您。",
    "Keybinding: editor.action.inlineSuggest.acceptNextWord": "快捷键: editor.action.inlineSuggest.acceptNextWord",
    "Keybinding: ": "快捷键: ",
    "Customize your Cursor experience": "自定义你的 Cursor 体验",
    "Choose between light, dark, or high contrast themes": "在浅色、深色或高对比度主题之间选择",
    "Tool Call Density": "工具调用密度",
    "Adjust how much detail is shown for tool calls": "调整工具调用显示的详细程度",
    "UI Font Size": "界面字体大小",
    "Font size for the Cursor user interface": "Cursor 用户界面的字体大小",
    "Code Font Size": "代码字体大小",
    "Font size for code editors and diffs": "代码编辑器和差异视图的字体大小",
    "UI Font Family": "界面字体",
    "Reduce Transparency": "降低透明度",
    "VS Code Settings": "VS Code 设置",
    "Local Automations": "本地自动化",
    "Automations": "自动化",
    "Show rotating tips on the empty screen": "在空白界面显示轮换提示",
    "Auto-Approve Mode Transitions": "自动批准模式切换",
    "Allow Agent to switch modes without asking first, such as Agent to Plan or Agent to Debug. When off, Cursor asks before switching.": "允许智能体无需确认即可切换模式（如智能体到计划或智能体到调试）。关闭时，Cursor 会在切换前询问。",
    "Open Agents Window on startup": "启动时打开智能体窗口",
    "When launching Cursor, open Agents Window by default": "启动 Cursor 时默认打开智能体窗口",
    "Explore subagent model": "探索子智能体模型",
    "The Explore subagent is used to do initial research for the main agent": "探索子智能体用于为主智能体进行初步调研",
    "Browser Automation": "浏览器自动化",
    "Open Web Links in Browser": "在浏览器中打开网页链接",
    "Automatically open http and https links in the Browser Tab": "自动在浏览器标签页中打开 http 和 https 链接",
    "No User MCP Tools": "暂无用户 MCP 工具",
    "Add a custom MCP tool in your user MCP config.": "在用户 MCP 配置中添加自定义 MCP 工具。",
    "Add Custom MCP": "添加自定义 MCP",
    "Team MCP Servers": "团队 MCP 服务器",
    "Configured in the dashboard": "在控制台中配置",
    "Configure Team MCP Servers": "配置团队 MCP 服务器",
    "Cursor periodically removes old worktrees to free disk space. Tune how aggressively cleanup runs.": "Cursor 会定期清理旧工作树以释放磁盘空间。可调整清理策略的激进程度。",
    "Max worktrees": "最大工作树数量",
    "Maximum number of Cursor-managed worktrees to retain across all workspaces. Older worktrees are removed first.": "在所有工作区中保留的 Cursor 管理工作树的最大数量。优先移除较旧的工作树。",
    "Maximum number of Cursor-managed worktrees to keep across all workspaces. Older worktrees are removed first. Default is 25.": "在所有工作区中保留的 Cursor 管理工作树最大数量。优先移除较旧工作树。默认值为 25。",
    "Max total size (GB)": "最大总大小 (GB)",
    "Maximum total size in GB across all Cursor-managed worktrees. Set to 0 to disable the size limit.": "所有 Cursor 管理工作树的最大总大小（GB）。设为 0 可禁用大小限制。",
    "Maximum total size in GB for the Cursor worktrees directory across all workspaces. Set to 0 to disable this limit.": "所有工作区中 Cursor 工作树目录的最大总大小（GB）。设为 0 可禁用此限制。",
    "Cursor-managed worktrees": "Cursor 管理的工作树",
    "No Cursor-managed worktrees on this machine.": "此机器上没有 Cursor 管理的工作树。",
    "New Terminal": "新建终端",
    "New Browser": "新建浏览器",
    "Open Editor Window": "打开编辑器窗口",
    "Exit": "退出",

    // ── 标准菜单项（Edit / View / Help）──
    "Select All": "全选",
    "Command Palette": "命令面板",
    "View License": "查看许可证",
    "Zoom In": "放大",
    "Zoom Out": "缩小",
    "Reset Zoom": "重置缩放",
    "About": "关于",
    "Keyboard Shortcuts": "键盘快捷键",

    // ── Tab 补全设置 ──
    "Ignored Files": "忽略的文件",
    "Glob patterns for files where Cursor Tab will not suggest": "Cursor Tab 不会提供建议的文件的 Glob 模式",
    "e.g., *.md, **/generated/**": "例如：*.md、**/generated/**",

    // ── 套餐名称 ──
    "Pro Plan": "Pro 版",
    "Pro Trial": "Pro 试用",
    "Pro+ Plan": "Pro+ 版",
    "Pro+ Trial": "Pro+ 试用",
    "Free Plan": "免费版",
    "Ultra Plan": "Ultra 版",
    "Enterprise Plan": "企业版",
    "Start Trial": "开始试用",

    // ── 账号 / 计费设置 ──
    "Sign In": "登录",
    "Sign in to get started with Cursor's AI features": "登录以开始使用 Cursor 的 AI 功能",
    "API Key": "API 密钥",
    "Connect Slack": "连接 Slack",
    "Manage Settings": "管理设置",
    "Connect GitHub/GitLab, manage team and user settings, and configure environments": "连接 GitHub/GitLab，管理团队和用户设置，并配置环境",
    "On-Demand": "按需",
    "On-Demand Usage": "按需用量",
    "On-Demand Spending": "按需消费",
    "Enable on-demand usage to go beyond your plan's included usage. Requires a paid plan.": "启用按需用量以超出套餐包含的额度。需要付费套餐。",
    "Monthly Limit": "月度限额",
    "Set a fixed amount or make it unlimited.": "设置固定额度或设为无限制。",
    "Total": "总计",

    // ── 模型 / 区域设置 ──
    "Region": "区域",
    "Deployment Name": "部署名称",
    "Secret Access Key": "秘密访问密钥",
    "Override OpenAI Base URL": "覆盖 OpenAI 基础 URL",
    "Change the base URL for OpenAI API requests.": "更改 OpenAI API 请求的基 URL。",
    "Test Model": "测试模型",

    // ── 智能体 / 终端设置（补充）──
    "Auto-Run Network Access": "自动运行网络访问",
    "Control which network requests are allowed when commands run in the sandbox. Edit allowed/denied domains in sandbox.json in your workspace.": "控制命令在沙箱中运行时允许的网络请求。在工作区的 sandbox.json 中编辑允许/拒绝的域名。",
    "Auto-Run On Agent Finish": "智能体完成时自动运行",
    "Automatically run Review when Agent finishes and has made file changes": "当智能体完成并已修改文件时自动运行审查",
    "Compact Terminal Tool Calls": "精简终端工具调用",
    "Show terminal commands in compact view by default": "默认以精简视图显示终端命令",
    "Follow-Up Prompt Suggestions": "后续提示建议",

    // ── 编辑器 / 界面设置（补充）──
    "Cmd+K: Escape focuses the editor when you have a diff": "有差异时 Esc 聚焦编辑器",
    "Make escape focus editor instead of closing the prompt bar": "按 Esc 时聚焦编辑器，而不是关闭提示栏",
    "Force View Zones": "强制显示视图区域",
    "Force the display of view zones in the editor": "强制在编辑器中显示视图区域",
    "Show view zone when preview box is clipped": "预览框被裁剪时显示视图区域",
    "Show a view zone when the preview box is clipped": "当预览框被裁剪时显示视图区域",
    "Open chat as editor tabs": "以编辑器标签页打开聊天",
    "Title Bar": "标题栏",
    "Show title bar in agent layout": "在智能体布局中显示标题栏",

    // ── 开发者 / 诊断设置 ──
    "Disposable Tracking": "Disposable 追踪",
    "Enable Disposable Tracking": "启用 Disposable 追踪",
    "Leak Detection": "泄漏检测",
    "Enable leak detection console output": "启用泄漏检测控制台输出",
    "Solid Dev Tools": "Solid 开发工具",
    "Enable Solid Dev Tools": "启用 Solid 开发工具",
    "Cpp Control Token": "Cpp 控制令牌",
    "Control tokens control how likely the model is to produce no-ops. Will be replaced with auto-selection": "控制令牌决定模型产生空操作的可能性。将被自动选择取代",
    "Verify Extension Signatures": "验证扩展签名",

    // ── 占位符 / 按钮文案 ──
    "Add domains...": "添加域名...",
    "Add MCP tools...": "添加 MCP 工具...",
    "Copied": "已复制",
    "Copy code": "复制代码",
    "Copy link": "复制链接",
    "Copy results": "复制结果",
    "Copy commit SHA": "复制提交 SHA",
    "Show Logs": "显示日志",
    "Hide Logs": "隐藏日志",

    // ── 设置页按钮 / Beta 通道 ──
    "Configure Ignored Files": "配置忽略的文件",
    "Compute index": "计算索引",
    "Update Access is managed by internal release-track policy.": "更新通道由内部发布轨道策略管理。",
    "Open Statsig config": "打开 Statsig 配置",
    "⚠️ Warning: Updates Apply Automatically": "⚠️ 警告：更新将自动应用",
    "This track will silently download and install updates without prompting whenever Cursor is closed.": "此通道将在 Cursor 关闭时静默下载并安装更新，不会提示您。",

    // ── 通用设置页（General / Appearance）──
    "Window Layout": "窗口布局",
    "Switch between Agent and Editor default layouts": "在智能体与编辑器默认布局之间切换",
    "Conversation Density": "对话密度",
    "Choose how much detail Agent tool calls show in the conversation": "选择智能体工具调用在对话中显示的详细程度",
    "Review Control Location": "审查控件位置",
    "Show inline diff review controls in top level breadcrumbs or floating island": "在顶层面包屑或浮动岛中显示内联差异审查控件",
    "Show status bar at the bottom of the window": "在窗口底部显示状态栏",
    "Compact": "精简",
    "Balanced": "平衡",
    "Detailed": "详细",
    "Breadcrumb": "面包屑",
    "Island": "浮动岛",

    // ── File 菜单 ──
    "New Agents Window": "新建智能体窗口",
    "New Agents Window (Glass)": "新建智能体窗口 (Glass)",
    "Close Window": "关闭窗口",
    "Agents Window": "智能体窗口",
    "Open Agents Window": "打开智能体窗口",
    "Use in Agents Window": "在智能体窗口中使用",
    "Meet the new Agents Window": "了解全新智能体窗口",
    "Switch to Agents Window": "切换到智能体窗口",
    "Switch to Agents Window (Glass)": "切换到智能体窗口 (Glass)",
    "Open or Focus Agents Window (Glass)": "打开或聚焦智能体窗口 (Glass)",
    "Developer: New Additional Agents Window": "开发者：新建额外智能体窗口",
    "Run cloud agents using the new Agents Window": "使用新的智能体窗口运行云端智能体",
    "Jump back to the Agents Window to keep working across repos.": "返回智能体窗口以跨仓库继续工作。",

    // ── 安装损坏提示（nls 兜底）──
    "Your {0} installation appears to be corrupt. Please reinstall.": "您的 {0} 安装似乎已损坏。请重新安装。",
    "More Information": "更多信息",
    "Don't Show Again": "不再显示",

    // ── 源代码管理 / Git 面板 ──
    "Use a Git repository to track changes": "使用 Git 仓库来跟踪更改",
    "Initialize Repository": "初始化仓库",
    "Uncommitted": "未提交",
    "Unstaged": "未暂存",
    "Staged": "已暂存",
    "Branch": "分支",
    "Local Changes": "本地更改",
    "Cloud Changes": "云端更改",
    "PR Changes": "PR 更改",
    "All Branch Changes": "全部分支更改",
    "Uncommitted Changes": "未提交的更改",
    "Move to Local": "移至本地",
    "Failed to initialize repository": "初始化仓库失败",
    "Expand All": "全部展开",
    "Collapse All": "全部折叠",
    "Show Cloud Changes": "显示云端更改",
    "No unstaged changes": "没有未暂存的更改",
    "No staged changes": "没有已暂存的更改",
    "No branch changes": "没有分支更改",
    "No changes in selected commits": "所选提交中没有更改",
    "No uncommitted changes on your local branch": "本地分支上没有未提交的更改",
    "All changes have been pushed to the remote branch": "所有更改已推送到远程分支",
    "No changes on this cloud agent's branch yet": "云端智能体分支上尚无更改",

    // ── Glass 侧边栏顶部标签 / 环境徽章 ──
    "Cloud Desktop": "云端桌面",
    "Target environment: local": "目标环境：本地",
    "Target environment: cloud": "目标环境：云端",

    // ── Glass 文件页 ──
    "No workspace folder open": "未打开工作区文件夹",
    "Loading workspace\u2026": "正在加载工作区…",
    "Open a file to get started": "打开文件以开始",
    "Select a file to view": "选择要查看的文件",
};

const riskyShortWords = {
    "General": "通用",
    "Appearance": "外观",
    "Worktrees": "工作树",
    "Indexing": "索引",
    "Home": "主页",
    "Back": "返回",
    "Theme": "主题",
    "Colors": "颜色",
    "Typography": "排版",
    "Hue": "色相",
    "Intensity": "强度",
    "Chat": "聊天",
    "Agents": "智能体",
    "Tab": "Tab 补全",
    "Models": "模型",
    "Plugins": "插件",
    "Hooks": "钩子",
    "Network": "网络",
    "Beta": "测试功能",
    "Marketplace": "插件市场",
    "Docs": "官方文档",
    "Open": "打开",
    "Invite": "邀请",
    "Import": "导入",
    "Show": "显示",
    "Auto-Run": "自动运行",
    "Pane": "面板",
    "Small": "小",
    "Default": "默认",
    "Large": "大",
    "Imports": "导入",
    "Rules": "规则",
    "Skills": "技能",
    "Subagents": "子智能体",
    "Commands": "命令",
    "Unlimited": "无限制",
    "Custom": "自定义",
    "Auto": "自动",
    "Always": "始终",
    "Never": "从不",
    "Quick": "快速",
    "Deep": "深度",
    "Context": "上下文",
    "Log Out": "退出登录",
    "Open Folder": "打开文件夹",
    "Browse Marketplace": "浏览插件市场",
    "Suggested": "推荐",
    "Copy Domains": "复制域名",
    "Run Diagnostic": "运行诊断",
    "Development": "开发",
    "Early Access": "抢先体验",
    "Nightly": "Nightly",
    "Configured Hooks": "已配置的钩子",
    "Execution Log": "执行日志",
    "Clear log": "清空日志",
    "Tools": "工具",
    "Browser": "浏览器",
    "Installed MCP Servers": "已安装的 MCP 服务器",
    "Off": "关闭",
    "Browser Tab": "浏览器标签页",
    "Cancel": "取消",
    "Confirm": "确认",
    "Hide": "隐藏",
    "Edit": "编辑",
    "Tips": "提示",
    "Cleanup": "清理",
    "Contact": "联系我们",
    "File": "文件",
    "View": "查看",
    "Help": "帮助",

    // ── Edit 菜单短词 ──
    "Undo": "撤销",
    "Redo": "重做",
    "Cut": "剪切",
    "Copy": "复制",
    "Paste": "粘贴",

    // ── View 菜单短词 ──
    "Changes": "更改",
    "Files": "文件",
    "Terminal": "终端",
    "Environment": "环境",
    "Settings": "设置",
};

module.exports = { safeGlobalDict, riskyShortWords };
